version: "0.1"
services:
  frontend:
    container_name: "domain_example_fe"
    image: "domain_example_fe"
    build:
      target: base
      context: .
      dockerfile: "Dockerfile"
      cache_from: 
        - node:latest
    networks:
      - domain_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    ports:
      - "8081:8081"

networks:
  domain_network:
    name: domain_example
    driver: bridge
